# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

throw "Replace ./system/hardware-configuration.nix with:\nnixos-generate-config --show-hardware-config > ./system/hardware-configuration.nix"
